"""Shared validation and authentication security helpers."""
import hashlib
import hmac
import re
from datetime import datetime, timedelta
from flask import current_app
from sqlalchemy.exc import IntegrityError
from werkzeug.security import check_password_hash

from models import db, RateLimitBucket


EMAIL_RE = re.compile(r'^[^\s@]{1,64}@[^\s@]{1,190}\.[A-Za-z]{2,63}$')
USERNAME_RE = re.compile(r'^[A-Za-z0-9][A-Za-z0-9_.-]{2,49}$')
RECOVERY_HASH_PREFIX = 'hmac-sha256$'


def valid_email(value: str) -> bool:
    return bool(value and len(value) <= 254 and EMAIL_RE.fullmatch(value))


def valid_username(value: str) -> bool:
    return bool(value and USERNAME_RE.fullmatch(value))


def _normalise_recovery_code(value: str) -> str:
    return (value or '').strip().upper()


def hash_recovery_code(value: str) -> str:
    """Hash a random recovery code without a CPU-heavy password KDF.

    Recovery codes are generated by the application rather than selected by a
    user. A keyed digest therefore prevents offline checking after a database-
    only compromise while keeping 2FA setup responsive on small instances.
    """
    key = str(current_app.secret_key).encode('utf-8')
    digest = hmac.new(
        key,
        _normalise_recovery_code(value).encode('utf-8'),
        hashlib.sha256,
    ).hexdigest()
    return RECOVERY_HASH_PREFIX + digest


def verify_recovery_code(stored_hash: str, candidate: str) -> bool:
    """Verify current keyed hashes and legacy Werkzeug recovery-code hashes."""
    if not stored_hash or not candidate:
        return False
    if stored_hash.startswith(RECOVERY_HASH_PREFIX):
        expected = hash_recovery_code(candidate)
        return hmac.compare_digest(stored_hash, expected)
    try:
        return check_password_hash(stored_hash, _normalise_recovery_code(candidate))
    except (TypeError, ValueError):
        return False


def consume_rate_limit(scope: str, identity: str, maximum: int, window_seconds: int) -> bool:
    """Return True when blocked; counters survive restarts and multiple workers."""
    identity_hash = hashlib.sha256((identity or 'unknown').encode('utf-8')).hexdigest()
    now = datetime.utcnow()
    bucket = RateLimitBucket.query.filter_by(
        scope=scope, identity_hash=identity_hash
    ).with_for_update().first()
    if not bucket:
        db.session.add(RateLimitBucket(scope=scope, identity_hash=identity_hash, attempts=1, window_start=now))
        try:
            db.session.commit()
            return False
        except IntegrityError:
            # Another worker created this unique bucket after our SELECT.
            # Roll back and process this request against that shared row.
            db.session.rollback()
            bucket = RateLimitBucket.query.filter_by(
                scope=scope, identity_hash=identity_hash
            ).with_for_update().first()
            if not bucket:
                raise
    if now - bucket.window_start >= timedelta(seconds=window_seconds):
        bucket.window_start = now
        bucket.attempts = 1
        db.session.commit()
        return False
    if bucket.attempts >= maximum:
        return True
    bucket.attempts += 1
    db.session.commit()
    return False


def clear_rate_limit(scope: str, identity: str) -> None:
    identity_hash = hashlib.sha256((identity or 'unknown').encode('utf-8')).hexdigest()
    RateLimitBucket.query.filter_by(scope=scope, identity_hash=identity_hash).delete()
    db.session.commit()
